---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: harbor.sys.pks.wrightcode.io/tools/pipeline-base/pipeline-base
    tag: latest
inputs:
  - name: tools
  - name: repo
  - name: keyval
outputs:
  - name: out
  - name: keyvalout
caches:
  - path: gradle
  - path: maven
run:
  path: microservices-springboot-docker/ci/tasks/build-and-upload/task.sh
