# Disable Spring Cloud and Zipkin
spring:
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        input:
          destination: venuetopic
          content-type: application/json
          group: venuegroup
          resetOffsets: true
      kafka:
        binder:
          brokers: localhost:9092
        filter: test
    config:
      enabled: false
  zipkin:
    enabled: false
  data:
    couchbase:
      auto-index: false
  couchbase:
    bootstrap-hosts: localhost:8091
    bucket:
      name: shipwright
      password: p1v0tal
    env:
      ssl:
        enabled: false

security:
  oauth2:
    client:
      clientId: carnival
      clientSecret: carnival
      accessTokenUri: http://localhost:8080/openam/oauth2/carnival/access_token
      userAuthorizationUri: http://localhost:8080/openam/oauth2/carnival/authorize
      tokenName: access_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      token-info-uri: http://localhost:8080/openam/oauth2/carnival/tokeninfo
    scope: all
# Disable security
#security:
#  ignored: /**

###
# Actuator
###
endpoints:
  health:
    sensitive: false
    
server:
  port: 8081

management:
  port: ${server.port}
  context-path: /admin
  info.git.mode: full
  security:
    enabled: false

###
# Logging Configuration
###
logging:
  level:
    root: INFO
    org:
      springframework: 
        security: DEBUG
      hibernate: ERROR
    com.example: INFO
  file: ./log/application.log

eureka:
  client:
    enabled: false
