platform: linux

image_resource:
  type: docker-image
  source:
    repository: mwrightpivotal/pcf
    tag: latest

inputs:
  - name: pcf-ers-demo

run:
  path: sh
  args:
  - -exc
  - |
    pcf-ers-demo/mvnw -f pcf-ers-demo/pom.xml package
    cf local stage pcf-ers-demo -p target/pcf-ers-demo.jar

params:
  MAVEN_BASEDIR: pcf-ers-demo
