platform: linux

image_resource:
  type: docker-image
  source:
    repository: mwrightpivotal/pcf
    tag: latest

inputs:
  - name: daytrader

run:
  path: sh
  args:
  - -exc
  - |
    daytrader/mvnw -f daytrader/pom.xml package
    cf login -a $PCF_TARGET_URL --skip-ssl-validation -u $PCF_USERNAME -p $PCF_PASSWORD -o $PCF_ORG -s $PCF_SPACE
    cf zero-downtime-push $APP_NAME -f daytrader/manifest.yml

params:
  MAVEN_BASEDIR: daytrader