platform: linux

image_resource:
  type: docker-image
  source:
    repository: mwrightpivotal/pcf
    tag: latest

inputs:
  - name: boottrader

run:
  path: sh
  args:
  - -exc
  - |
    wget -O boottrader-worker.tar $DOTNET_RELEASE_URL
    tar -xvf boottrader-worker.tar 
    cf login -a $PCF_TARGET_URL --skip-ssl-validation -u $PCF_USERNAME -p $PCF_PASSWORD -o $PCF_ORG -s $PCF_SPACE
    cf push ci-boottrader-worker -b hwc_buildpack -s windows2016 -p PublishOutput/. --no-start
    cf bs ci-boottrader-worker df-rabbit
    cf restage ci-boottrader-worker

params:
  MAVEN_BASEDIR: boottrader
