platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/cloudfoundry
    tag: latest

inputs:
  - name: pcf-ers-demo

run:
  path: sh
  args:
  - -exc
  - |
    sed -e "s/String appVersion = \"2.0\";/String appVersion = \"1.0\";/" -i ./pcf-ers-demo/src/main/java/io/pivotal/pcf/sme/ers/client/ui/controller/AttendeeService.java
    sed -e "s/String appVersion = \"CANARY\";/String appVersion = \"1.0\";/" -i ./pcf-ers-demo/src/main/java/io/pivotal/pcf/sme/ers/client/ui/controller/AttendeeService.java
    pcf-ers-demo/mvnw -f pcf-ers-demo/pom.xml package -DskipTests=true
    cf login -a $PCF_TARGET_URL --skip-ssl-validation -u $PCF_USERNAME -p $PCF_PASSWORD -o $PCF_ORG -s $PCF_SPACE
    cf push $APP_NAME -f pcf-ers-demo/manifest.yml -p pcf-ers-demo/target/pcf-ers-demo.jar

params:
  MAVEN_BASEDIR: pcf-ers-demo