platform: linux

image_resource:
  type: docker-image
  source:
    repository: mwrightpivotal/pcf
    tag: latest

inputs:
  - name: shipwright

run:
  path: sh
  args:
  - -exc
  - |
    mvn -f shipwright/pom.xml package

params:
  MAVEN_BASEDIR: shipwright
