version: '2'
services:
  couchbasedb:
    image: shipwright/couchbasedb
    container_name: couchbasedb
    hostname: couchbasedb
    ports:
     - "8091-8093:8091-8093"
     - "11210:11210"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   -ref-config-service
    hostname: sb-ref-config-service
    restart: always
    ports:
     - "11111:8080"
    links:
     - eureka
    depends_on:
     - eureka
  auth:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ACME_SERVICE_SECRET: acmesecret
      EDGE_SERVICE_SECRET: edgesecret
      RESERVATION_SERVICE_SECRET: reservationsecret
      VENUE_SERVICE_SECRET: venuesecret
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
      JAVA_OPTS: -Xmx4g
    image: shipwright/sb-ref-auth-service:1.0.0-SNAPSHOT
    container_name: sb-ref-auth-service
    hostname: sb-ref-auth-service
    restart: always
    ports:
     - "11102:8080"
    links:
     - configserver
    depends_on:
     - configserver
  composite:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
      KAFKA_HOSTS: "kafka:9092"
      JAVA_OPTS: -Xmx4g
    image: shipwright/sb-ref-composite-service:1.0.0-SNAPSHOT
    container_name: sb-ref-composite-service
    hostname: sb-ref-composite-service
    restart: always
    ports:
     - "11103:8080"
  gateway:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
    image: shipwright/sb-ref-edge-service:1.0.0-SNAPSHOT
    container_name: sb-ref-edge-service
    hostname: sb-ref-edge-service
    restart: always
    ports:
    - "11104:8080"
  hystrix:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
    image: shipwright/sb-ref-hystrix-dashboard:1.0.0-SNAPSHOT
    container_name: sb-ref-hystrix-dashboard
    hostname: sb-ref-hystrix-dashboard
    restart: always
    ports:
     - "11105:8080"
  reservation:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
      JAVA_OPTS: -Xmx4g
    image: shipwright/sb-ref-reservation-service:1.0.0-SNAPSHOT
    container_name: sb-ref-reservation-service
    hostname: sb-ref-reservation-service
    restart: always
    ports:
      - "11106:8080"
  venue:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
      COUCHBASE_IP: couchbasedb
      KAFKA_HOSTS: "kafka:9092"
    image: shipwright/sb-ref-venue-service:1.0.0-SNAPSHOT
    container_name: sb-ref-venue-service
    hostname: sb-ref-venue-service
    restart: always
    ports:
      - "11107:8080"
  zipkin:
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_HOST: sb-ref-config-service
      CONFIG_PORT: 8080
    image: shipwright/sb-ref-zipkin-service:1.0.0-SNAPSHOT
    container_name: sb-ref-zipkin-service
    hostname: sb-ref-zipkin-service
    restart: always
    ports:
       - "11108:8080"
       - "11109:9411"
       - "11110:9901"