management:
  port: ${server.port}
  context-path: /admin
  security:
    enabled: false

server:
  context-path: /uaa

info:
  component: OAuth Server

security:
  sessions: if_required
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      authorized-grant-types: authorization_code,refresh_token,implicit,password,client_credentials
      scope: server
    resource:
      filter-order: 3

logging:
  level:
    org.springframework.security: DEBUG

spring:
  cloud:
    config:
      enabled: true

eureka:
  client:
    enabled: true